name: "Grumpy"
author: "@jamieRowen"
description: "Run grumpy checks against your source code"
inputs:
  grumpy-version:
    description: "The version of grumpy_checks to install"
    required: true
    default: "0.1.6"

runs:
  using: "composite"
  steps:
    - run: |
        pip install grumpy_checks==${{ inputs.grumpy-version }}
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: grumpy-report
        path: grumpy_report